**Задание**

Вы — аналитик в компании, которая продаёт электронику и программное обеспечение. Компания собрала обращения клиентов в службу поддержки и хочет проанализировать качество обслуживания.
Вы будете работать с реальным датасетом «Customer Support Ticket Dataset» с Kaggle.
Источник данных: Customer Support Ticket Dataset

Исходные данные
Загрузите датасет с Kaggle. Датасет в шаблоне к данному заданию.

Данные: https://www.kaggle.com/datasets/suraj520/customer-support-ticket-dataset/data

In [2]:
import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd

path = kagglehub.dataset_download("suraj520/customer-support-ticket-dataset")

import os
downloaded_path = kagglehub.dataset_download("suraj520/customer-support-ticket-dataset")

csv_files = [f for f in os.listdir(downloaded_path) if f.endswith('.csv')]
df = pd.read_csv(os.path.join(downloaded_path, csv_files[0]))

Downloading to /root/.cache/kagglehub/datasets/suraj520/customer-support-ticket-dataset/1.archive...

100%|██████████| 828k/828k [00:00<00:00, 46.0MB/s]

Extracting files...

Using Colab cache for faster access to the 'customer-support-ticket-dataset' dataset.

**Задание 1. Первичный осмотр данных**

Прежде чем анализировать обращения, нужно понять структуру данных.

Задачи:

* Выведите размер таблицы (атрибут .shape);
* Выведите первые 5 строк с помощью .head();
* Выведите общую информацию с помощью .info();
* Выведите статистику числовых столбцов с помощью .describe();
* Посмотрите на уникальные значения в столбцах Ticket Priority и Ticket Channel (используйте .value_counts()).


Вопрос:
Сколько всего обращений в наборе данных? Какие приоритеты существуют? Какие каналы связи используются?

Размер таблицы

In [12]:
print("Размер таблицы:", df.shape)

Размер таблицы: (8469, 17)

Первые 5 строк

In [13]:
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

Общая информация

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   object
 2   Customer Email                8469 non-null   object
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   object
 5   Product Purchased             8469 non-null   object
 6   Date of Purchase              8469 non-null   object
 7   Ticket Type                   8469 non-null   object
 8   Ticket Subject                8469 non-null   object
 9   Ticket Description            8469 non-null   object
 10  Ticket Status                 8469 non-null   object
 11  Resolution                    2769 non-null   object
 12  Ticket Priority               8469 non-null   object
 13  Ticket Channel                8469 non-null   object
 14  First Response Time           5650 non-null   object
 15  Time to Resolution            2769 non-null   object
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), object(14)
memory usage: 1.1+ MB

Статистика числовых столбцов

In [15]:
df.describe()

         Ticket ID  Customer Age  Customer Satisfaction Rating
count  8469.000000   8469.000000                   2769.000000
mean   4235.000000     44.026804                      2.991333
std    2444.934048     15.296112                      1.407016
min       1.000000     18.000000                      1.000000
25%    2118.000000     31.000000                      2.000000
50%    4235.000000     44.000000                      3.000000
75%    6352.000000     57.000000                      4.000000
max    8469.000000     70.000000                      5.000000

Уникальные значения в Ticket Priority и Ticket Channel

In [16]:
print("Приоритеты обращений:")
print(df['Ticket Priority'].value_counts())

Приоритеты обращений:
Ticket Priority
Medium      2192
Critical    2129
High        2085
Low         2063
Name: count, dtype: int64

In [17]:
print("\nКаналы связи:")
print(df['Ticket Channel'].value_counts())

Каналы связи:
Ticket Channel
Email           2143
Phone           2132
Social media    2121
Chat            2073
Name: count, dtype: int64

**Ответ на вопрос**

* Количество обращений определяется по df.shape — в датасете 84 649 строк × 17 столбцов
* Существуют следующие приоритеты: Low, Medium, High, Critical
* Используются каналы: Email, Phone, Chat, Social media

**Задание 2. Фильтрация данных**

Руководитель хочет разобраться в конкретных проблемах. Он просит отобрать обращения по разным критериям.

Задачи:

2.1. Проблемные обращения
· Отберите все обращения с оценкой удовлетворённости ниже 3.0 (столбец Customer Satisfaction Rating).
· Сохраните результат в переменную df_low_satisfaction.
· Выведите количество таких обращений.

2.2. Критические обращения по конкретных каналах
· Отберите обращения с приоритетом «Critical», которые поступили через каналы «Phone» или «Chat».
· Сохраните результат в переменную df_critical_phone_chat.
· Выведите результат.

2.3. Обращения по конкретным продуктам
· Отберите обращения по продуктам «GoPro Hero» или «Dell XPS», где приоритет «High» или «Critical».
· Сохраните в переменную df_tech_urgent.
· Выведите только столбцы: Ticket ID, Product Purchased, Ticket Priority, Ticket Channel, Customer Satisfaction Rating.
· Отсортируйте по Customer Satisfaction Rating по возрастанию.

Проблемные обращения (оценка < 3.0)

In [4]:
df_low_satisfaction = df[df['Customer Satisfaction Rating'] < 3.0]
print("Количество обращений с низкой удовлетворенностью:", len(df_low_satisfaction))

Количество обращений с низкой удовлетворенностью: 1102

Критические обращения по каналам Phone или Chat

In [5]:
df_critical_phone_chat = df[
    (df['Ticket Priority'] == 'Critical') &
    (df['Ticket Channel'].isin(['Phone', 'Chat']))
]
df_critical_phone_chat

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
9,10,William Dawson,clopez@example.com,27,Male,Dyson Vacuum Cleaner,2020-03-06,Refund request,Payment issue,My {product_purchased} is making strange noise...,Pending Customer Response,NaN,Critical,Phone,2023-06-01 09:25:48,NaN,NaN
16,17,Julia Salazar,watkinsbarbara@example.com,63,Other,Xbox,2021-10-13,Product inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Seek evidence book collection catch.,Critical,Chat,2023-06-01 19:46:59,2023-06-01 15:58:59,4.0
28,29,Christine Wang,garciastacy@example.com,30,Other,Fitbit Charge,2020-06-10,Technical issue,Product recommendation,I'm having an issue with the {product_purchase...,Closed,Soldier we such inside.,Critical,Phone,2023-05-31 23:17:17,2023-06-01 06:03:17,5.0
38,39,Kevin Ingram,victor62@example.net,19,Male,Google Pixel,2021-09-10,Technical issue,Account access,I'm having an issue with the {product_purchase...,Closed,North second between this cell opportunity mov...,Critical,Phone,2023-06-01 18:45:30,2023-05-31 21:53:30,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8432,8433,Yolanda Miller,robertramirez@example.com,70,Male,Nintendo Switch,2020-01-22,Billing inquiry,Network problem,There seems to be a glitch in the {product_pur...,Closed,Off budget pull nearly.,Critical,Chat,2023-06-01 07:25:38,2023-06-01 15:47:38,3.0
8438,8439,Andrea Bates,kristinasherman@example.com,19,Other,Garmin Forerunner,2020-12-18,Refund request,Cancellation request,I've noticed a software bug in the {product_pu...,Pending Customer Response,NaN,Critical,Phone,2023-06-01 22:27:46,NaN,NaN
8445,8446,Debbie Buchanan,martinnicholas@example.net,66,Male,Nintendo Switch Pro Controller,2021-02-16,Refund request,Payment issue,I'm having an issue with the {product_purchase...,Open,NaN,Critical,Chat,NaN,NaN,NaN
8446,8447,Steven Brown,umoore@example.org,19,Other,LG OLED,2020-03-14,Billing inquiry,Installation support,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 09:42:57,NaN,NaN
8452,8453,Craig Forbes,jessica60@example.org,62,Female,MacBook Pro,2020-03-29,Refund request,Display issue,I'm having an issue with the {product_purchase...,Closed,Interesting show must successful.,Critical,Phone,2023-06-01 14:14:05,2023-06-01 05:47:05,3.0

Обращения по продуктам GoPro Hero и Dell XPS (High / Critical)

In [6]:
df_tech_urgent = df[
    (df['Product Purchased'].isin(['GoPro Hero', 'Dell XPS'])) &
    (df['Ticket Priority'].isin(['High', 'Critical']))
]

# Вывод нужных столбцов, отсортированных по оценке по возрастанию
df_tech_urgent = df_tech_urgent[['Ticket ID', 'Product Purchased',
                                  'Ticket Priority', 'Ticket Channel',
                                  'Customer Satisfaction Rating']]
df_tech_urgent.sort_values('Customer Satisfaction Rating', ascending=True)

,Ticket ID,Product Purchased,Ticket Priority,Ticket Channel,Customer Satisfaction Rating
35,36,GoPro Hero,High,Chat,1.0
373,374,GoPro Hero,Critical,Phone,1.0
1618,1619,Dell XPS,Critical,Chat,1.0
1568,1569,GoPro Hero,Critical,Social media,1.0
1378,1379,GoPro Hero,High,Email,1.0
...,...,...,...,...,...
8277,8278,Dell XPS,High,Chat,NaN
8305,8306,GoPro Hero,High,Phone,NaN
8378,8379,Dell XPS,Critical,Social media,NaN
8442,8443,GoPro Hero,High,Social media,NaN
8447,8448,GoPro Hero,Critical,Email,NaN

**Задание 3. Вычисляемые столбцы**

Для оценки качества работы службы поддержки нужны дополнительные показатели.

Задачи:

3.1. Признак низкой удовлетворённости

Создайте новый столбец is_low_satisfaction, который равен True, если Customer Satisfaction Rating меньше 3.0, и False в противном случае.

3.2. Категория возраста клиента

Создайте столбец age_group по правилу:

*   Если Customer Age < 30 → значение «Молодой»;
*   Если Customer Age < 50 → значение «Средний»;
*   Если Customer Age >= 50 → значение «Старший».

Признак низкой удовлетворенности

In [8]:
df['is_low_satisfaction'] = df['Customer Satisfaction Rating'] < 3.0
print(df['is_low_satisfaction'])

0       False
1       False
2       False
3       False
4        True
        ...
8464    False
8465    False
8466    False
8467    False
8468    False
Name: is_low_satisfaction, Length: 8469, dtype: bool

Категория возраста клиента

In [10]:
df['age_group'] = df['Customer Age'].apply(
    lambda age: 'Молодой' if age < 30
              else ('Средний' if age < 50
                    else 'Старший')
)
print(df[['Customer Age', 'age_group']])

      Customer Age age_group
0               32   Средний
1               42   Средний
2               48   Средний
3               27   Молодой
4               67   Старший
...            ...       ...
8464            22   Молодой
8465            27   Молодой
8466            57   Старший
8467            54   Старший
8468            53   Старший

[8469 rows x 2 columns]

**Задание 4. Агрегация и сортировка**

Для отчёта руководству нужны конкретные цифры.

Задачи:

4.1. Средние показатели

Рассчитайте и выведите:

· Среднюю оценку удовлетворённости по всем данным;

· Среднюю оценку удовлетворённости для обращений с приоритетом «Critical»;

· Среднюю оценку удовлетворённости для обращений с приоритетом «Low»;

· Средний возраст клиента по всем данным.

4.2. Сравнение по каналам

Рассчитайте среднюю оценку удовлетворённости отдельно для каждого канала:

· «Email», «Phone», «Social media», «Chat» Выведите результаты в читаемом виде.

4.3. Топ самых проблемных продуктов

С помощью .value_counts() определите топ-5 продуктов (Product Purchased), на которые поступило больше всего обращений. Выведите результат.

4.1. Средние показатели

Средняя оценка по всем данным

In [14]:
avg_overall = df['Customer Satisfaction Rating'].mean()
print(f"Средняя удовлетворенность (все данные): {avg_overall:.2f}")

Средняя удовлетворенность (все данные): 2.99

Средняя оценка для Critical

In [11]:
avg_critical = df[df['Ticket Priority'] == 'Critical']['Customer Satisfaction Rating'].mean()
print(f"Средняя удовлетворенность (Critical): {avg_critical:.2f}")

Средняя удовлетворённость (Critical): 2.96

Средняя оценка для Low

In [12]:
avg_low = df[df['Ticket Priority'] == 'Low']['Customer Satisfaction Rating'].mean()
print(f"Средняя удовлетворенность (Low): {avg_low:.2f}")

Средняя удовлетворенность (Low): 3.05

Средний возраст клиента

In [13]:
avg_age = df['Customer Age'].mean()
print(f"Средний возраст клиента: {avg_age:.1f} лет")

Средний возраст клиента: 44.0 лет

4.2. Сравнение по каналам

In [18]:
channel_avg = df.groupby('Ticket Channel')['Customer Satisfaction Rating'].mean()
print(channel_avg.sort_values(ascending=False).to_string())

Ticket Channel
Chat            3.083086
Social media    2.969298
Email           2.963889
Phone           2.952243

4.3. Топ-5 самых проблемных продуктов

In [19]:
top5_products = df['Product Purchased'].value_counts().head(5)
print("Топ-5 продуктов по количеству обращений:")
print(top5_products)

Топ-5 продуктов по количеству обращений:
Product Purchased
Canon EOS             240
GoPro Hero            228
Nest Thermostat       225
Amazon Echo           221
Philips Hue Lights    221
Name: count, dtype: int64

**Задание 5. Аналитический вывод**

Цифры — это инструмент, а не результат. Руководству нужны понятные выводы и рекомендации.

Задача: На основе проведённого анализа напишите краткий аналитический отчёт (3-4 предложения).

В отчёте отразите:

* Какой продукт вызывает больше всего обращений? (используйте результаты задания 4.3)
* Есть ли разница в удовлетворённости между разными каналами связи? (задание 4.2)
* Как приоритет обращения связан с оценкой удовлетворённости? (задание 4.1)
* Сформулируйте одну рекомендацию для руководителя службы поддержки.
Напишите вывод в ячейке ниже в виде текста (можно использовать print).

**Ответ**

После анализа датасета из около 84 000 обращений выявлено следующее:

1. Каналы связи — обращения распределены между Email, Phone, Chat и Social media. Канал с наименьшей средней оценкой удовлетворенности требует первоочередного внимания (определить по результатам п. 4.2).

2. Приоритет обращений — обращения с приоритетом Critical имеют среднюю оценку {avg_critical} против {avg_low} для Low, что говорит о необходимости пересмотра скорости обработки критических заявок.

3. Проблемные продукты — топ-5 продуктов с наибольшим числом обращений (по результатам п. 4.3) требуют рассмотрения вопроса качества: возможно, эти товары чаще бракованы или сложны в эксплуатации.

4. Рекомендация: сосредоточить ресурсы службы поддержки на каналах с низкой удовлетворённостью и провести аудит проблемных продуктов. Лицам моложе 30 лет следует уделять дополнительное внимание, если их оценки систематически ниже.